CREATE TABLE clientes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome_cliente VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    data_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
